### ISSUE TITLE
Validate exported COMBINE archives to avoid providing users broken archives

### ISSUE THREAD

**Issue by jonrkarr** [PMR2/pmr2.omex#11]
Given that PMR is currently sometimes producing broken COMBINE archives (see #10), it seems that more validation is needed to ensure that PMR produces valid archives. In particular, it seems the CellML models should be validated before COMBINE archive creation to ensure that all needed files have been resolved.

**Comment by metatoaster** [comment]
They are all resolved provided the correct criteria is provided, and since I was instructed to roll this feature out quickly some of the legacy non-standard exposures created many years ago, predating the current standards and end up exhibiting unexpected behavior with this new feature might be expected.  It would be useful to indicate in the issue whether you have an issue with the software or the data in your issue request.

The failure reported in #10 was an exposure made and published many years ago as an experiment of what might a SED-ML exposure might look like in the future, and now we are in the future with formalized practices, that exposure is now outdated, thus the best outcome is to expire it and move on.

@nickerso Your input please.

**Comment by metatoaster** [comment]
Moreover, please concentrate your issues with more exposures with this particular incomplete inclusion to this issue by commenting on this issue with a new comment with links to them as I have validated that the software is working correctly provided that the current standards for file naming are being followed.

**Comment by jonrkarr** [comment]
I'm looking at this from a user's perspective. From that perspective, I'm expecting the software to work with all advertised data. As a user, I have limited information about what is old data and what is newer software. Ideally, users shouldn't have to think about this type of incompatibility. Typically, such incompatibilities are handled by migrating older data forward or retiring it.

**Comment by metatoaster** [comment]
However, this feature _was_ designed to be compatible with existing data, we have exactly _one_ failure of this type and it was because of a single published test exposure so far.  Your input is appreciated however but I will weigh it against the bigger picture here.

In general, we do test new features on the staging server but we have limited resource to test each and every link for this type of compatibility issues, we do rely on our users and reviewers to follow well established standards to avoid these type of issues.
