### ISSUE TITLE
The exported COMBINE archive for `e/5f0` does not include the SED-ML file

### ISSUE THREAD

**Issue by jonrkarr** [PMR2/pmr2.omex#12]
We noticed a case where we expected a SED-ML file to be exported with the COMBINE archive, but only the CellML file was included in the archive.

- Workspace with SED-ML file: [workspace/5d7/@@file/13d5908f9122600fb79960898a83637cc88798d6/](https://models.physiomeproject.org/workspace/5d7/@@file/13d5908f9122600fb79960898a83637cc88798d6/
)
- Archive: [e/5f0/download_generated_omex](https://models.physiomeproject.org/e/5f0/download_generated_omex)

@bilalshaikh42 is working around this by not using the export COMBINE archive feature.

**Comment by metatoaster** [comment]
Thanks for bringing this to our attention, the sedml file should be included due to the linkage done via the OpenCOR view at the exposure file.

This is currently not included, as the export feature as implemented thus far only track any paths that have a corresponding exposure file, and any other linked files that the export system knows how to export.

**Comment by metatoaster** [comment]
The linkage through the OpenCOR view is now known to the exporter as per 0e9c571, and has been staged to the staging instance.  Please see the corresponding exposure which is at: https://staging.physiomeproject.org/e/5f2

This will be released some time next week, can be done sooner if requested.

**Comment by metatoaster** [comment]
Now deployed onto production.
